package team.carrypigeon.backend.api.bo.domain.file;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * File metadata business object.
 * Used to describe a stored file and its basic attributes.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class CPFileInfo {

    /**
     * File id, globally unique, generated by IdUtil.generateId().
     */
    private long id;

    /**
     * Stable share key used by {@code GET /api/files/download/{share_key}}.
     * <p>
     * This is the primary identifier exposed to clients; it must be stable and unique.
     */
    private String shareKey;

    /**
     * Owner user id (uploader).
     */
    private long ownerUid;

    /**
     * Access scope for file download.
     * <p>
     * This controls who can download the file from {@code GET /api/files/download/{share_key}}.
     */
    private CPFileAccessScopeEnum accessScope;

    /**
     * Scope channel id (required when {@link #accessScope} is {@link CPFileAccessScopeEnum#CHANNEL}).
     */
    private long scopeCid;

    /**
     * Scope message id (reserved for P2+ "file bound to message" ACL).
     * <p>
     * When non-zero, it indicates the file is intended to be accessed through the referenced message.
     */
    private long scopeMid;

    /**
     * Original filename (optional).
     */
    private String filename;

    /**
     * SHA-256 digest of file content, hex string.
     */
    private String sha256;

    /**
     * File size in bytes.
     */
    private long size;

    /**
     * Underlying object name in object storage (e.g. MinIO).
     */
    private String objectName;

    /**
     * Optional mime type when uploading.
     */
    private String contentType;

    /**
     * Whether the binary object has been uploaded to object storage.
     * <p>
     * Upload is a two-step flow: create metadata first, then upload bytes.
     */
    private boolean uploaded;

    /**
     * Uploaded time (null if not uploaded).
     */
    private LocalDateTime uploadedTime;

    /**
     * Created time of this record.
     */
    private LocalDateTime createTime;
}
