package team.carrypigeon.backend.api.bo.domain.file;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;

/**
 * File metadata business object.
 * Used to describe a stored file and its basic attributes.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
public class CPFileInfo {

    /**
     * File id, globally unique, generated by IdUtil.generateId().
     */
    private long id;

    /**
     * SHA-256 digest of file content, hex string.
     */
    private String sha256;

    /**
     * File size in bytes.
     */
    private long size;

    /**
     * Underlying object name in object storage (e.g. MinIO).
     */
    private String objectName;

    /**
     * Optional mime type when uploading.
     */
    private String contentType;

    /**
     * Created time of this record.
     */
    private LocalDateTime createTime;
}
